name: Manually Sync Rules from Elastic Security to GitHub

on:
  workflow_dispatch:
    inputs:
      sync_rules_from_elastic:
        description: 'Sync rules from Elastic Security (true/false)'
        required: true
        default: 'false'

jobs:
  manual-dispatch-sync:
    runs-on: ubuntu-latest
    env:
      CUSTOM_RULES_DIR: ${{ secrets.CUSTOM_RULES_DIR }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip cache purge
        pip install .[dev]

    - name: Export and Import Rules if flag is true
      if: ${{ github.event.inputs.sync_rules_from_elastic == 'true' }}
      run: |
        # TODO: default to CUSTOM_RULES_DIR and remove --directory flags
        python -m detection_rules kibana export-rules  --directory ${{ env.CUSTOM_RULES_DIR }}
        python -m detection_rules import-rules-to-repo --directory ${{ env.CUSTOM_RULES_DIR }}
      env:
        KIBANA_URL: ${{ secrets.ELASTIC_KIBANA_URL }}
        KIBANA_USERNAME: ${{ secrets.ELASTIC_USERNAME }}
        KIBANA_PASSWORD: ${{ secrets.ELASTIC_PASSWORD }}

    - name: Update Version Lock
      run: |
        python -m detection_rules dev build-release --update-version-lock

    - name: Create Pull Request
      if: ${{ github.event.inputs.sync_rules_from_elastic == 'true' }}
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Sync rules from Elastic Security"
        title: "Sync rules from Elastic Security"
        body: "This PR syncs rules from Elastic Security to the repository for review."
        branch: "sync-rules-${{ github.run_id }}"
        delete-branch: true
        labels: "auto-update"

    - name: Commit Directly to Main
      if: ${{ github.event.inputs.sync_rules_from_elastic == 'false' }}
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add .
        git commit -m "Manual dispatch sync"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
