name: Sync Rule Tunings Per-PR to Elastic Security Dev Space

on:
  pull_request:
    branches: [ "*" ]
    types: [opened, synchronize, reopened, labeled, unlabeled]
    paths:
      - '**/*.toml'

jobs:
  sync-on-pr:
    runs-on: ubuntu-latest
    env:
      CUSTOM_RULES_DIR: ${{ secrets.CUSTOM_RULES_DIR }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip cache purge
        pip install .[dev]

    - name: Import Specific Rules Modified in PR
      run: |
        git fetch origin ${{ github.base_ref }} --depth=1
        git diff --name-only ${{ github.base_ref }} ${{ github.event.after }} '*.toml' | while read rule_file; do
          echo "Importing rule from file $rule_file"
          if [[ -f "$rule_file" ]]; then
            python -m detection_rules kibana import-rules --rule-file "$rule_file" --space "dev" --overwrite
          else
            echo "File does not exist: $rule_file"
          fi
        done
      env:
        DR_KIBANA_URL: ${{ secrets.ELASTIC_KIBANA_URL }}
        DR_KIBANA_USERNAME: ${{ secrets.ELASTIC_USERNAME }}
        DR_KIBANA_PASSWORD: ${{ secrets.ELASTIC_PASSWORD }}


